import {db} from "./firebase.js";import {collection,onSnapshot} from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
let categories=[],foods=[];let selected=new URLSearchParams(location.search).get("category")||"all";const tiles=document.getElementById("categoryTiles"),products=document.getElementById("categoryProducts");
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const imgs=p=>{const a=Array.isArray(p.images)?p.images.filter(Boolean):[];if(p.image&&!a.includes(p.image))a.unshift(p.image);return [...new Set(a)];};
function renderCategories(){tiles.innerHTML=`<button class="category-tile" data-id="all"><span class="icon">📦</span><strong>All Products</strong></button>`+categories.map(c=>`<button class="category-tile" data-id="${encodeURIComponent(c.name)}"><span class="icon">${esc(c.icon||"📦")}</span><strong>${esc(c.name)}</strong></button>`).join("");}
function renderProducts(){const list=selected==="all"?foods:foods.filter(f=>String(f.category||"").toLowerCase()===decodeURIComponent(selected).toLowerCase());products.innerHTML=`<h2>${selected==="all"?"All Products":esc(decodeURIComponent(selected))}</h2><section class="food-grid">${list.map(f=>{const im=imgs(f)[0];return `<div class="food-card"><div class="food-open-area" onclick="location.href='product.html?id=${encodeURIComponent(f.id)}'"><div class="food-image">${im?`<img src="${esc(im)}" alt="${esc(f.name)}">`:`<div class="no-image">📦</div>`}</div><h3>${esc(f.name)}</h3></div><div class="price">₹${Number(f.price||0)}</div><button class="add-cart" data-add="${f.id}" ${f.available===false?"disabled":""}>${f.available===false?"❌ Out Of Stock":"🛒 Add To Cart"}</button></div>`}).join("")||`<div class="empty-food">📦 No Products Found</div>`}</section>`;}
onSnapshot(collection(db,"categories"),s=>{categories=s.docs.map(d=>({id:d.id,...d.data()})).filter(c=>c.active!==false);renderCategories();});
onSnapshot(collection(db,"foods"),s=>{foods=s.docs.map(d=>({id:d.id,...d.data()}));renderProducts();});
document.addEventListener("click",e=>{const tile=e.target.closest(".category-tile");if(tile){selected=tile.dataset.id;history.replaceState(null,"",`category.html${selected==="all"?"":"?category="+selected}`);renderProducts();}const add=e.target.closest("[data-add]");if(add){const f=foods.find(x=>x.id===add.dataset.add);if(!f)return;let cart=JSON.parse(localStorage.getItem("cart"))||[];const ex=cart.find(i=>i.type!=="combo"&&i.id===f.id&&!i.selectedColor);if(ex)ex.qty++;else cart.push({id:f.id,name:f.name,image:imgs(f)[0]||"",images:imgs(f),price:Number(f.price||0),qty:1,selectedColor:""});localStorage.setItem("cart",JSON.stringify(cart));add.innerText="✓ Added";setTimeout(()=>add.innerText="🛒 Add To Cart",800);}});
window.renderBottomNav?.("category");
